# Generated by Django 6.1 on 2026-08-20 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='brief_description',
            new_name='description',
        ),
    ]
